---
title: "AED Location Map of NYC"
output: 
  html_document: 
    code_folding: hide 
---

```{r,setup, include=FALSE}
library(tidyverse)
library(stringr)
library(leaflet)
library(tigris)
library(sf)
library(RColorBrewer)
```


```{r, include=FALSE}
# Importing dataset

traffic_volume_df = read.csv("clean_data/traffic_clean.csv")

aed_inventory_df = read.csv("clean_data/aed_clean.csv")

```


```{r adding location variable, include=FALSE}
aed_clean = aed_inventory_df |>
  mutate(location = str_replace(location_point,"^POINT\\s*", "")
         )
```


```{r, setup of NYC Boroughs, include=FALSE}

boroughs = counties(state = "NY", cb = TRUE) |>
  filter(NAME %in% c("Bronx", "Kings", "New York", "Queens", "Richmond")) |>
  st_transform(4326) |>
  mutate(
    borough = case_when(
      NAME == "Bronx" ~ "Bronx",
      NAME == "Kings" ~ "Brooklyn",
      NAME == "New York" ~ "Manhattan",
      NAME == "Queens" ~ "Queens",
      NAME == "Richmond" ~ "Staten Island"
    )
  )

boro_pal <- colorFactor(
  palette = "Set1",
  domain = boroughs$borough
)
```


The map below displays AED locations across the boroughs. 
You can interact with the AED icons to explore:

* AED locations
* AED counts
* AED trained personnel



```{r, AED and borough mapping, echo=FALSE, fig.width=10, fig.height=7}

aed_map_icon <- makeIcon(
  iconUrl = "icons/map_logo.png",
  iconWidth = 10,             
  iconHeight = 15
)

leaflet() |>
  addProviderTiles(providers$CartoDB.Positron) |>
   addPolygons(
    data = boroughs,
    fillColor = ~boro_pal(borough),
    fillOpacity = 0.3,
    weight = 2,
    color = ~boro_pal(borough),
    popup = ~borough,
    group = "Boroughs"
  ) |>
   addLegend(
  "bottomright",
  pal = boro_pal,
  values = boroughs$borough,
  title = "Borough"
) |>
  addMarkers(
    data = aed_clean,
    lng = ~longitude,
    lat = ~latitude,
    icon = aed_map_icon,
    popup = ~paste0(
      "<b>Location Name: </b>", entity_name, "<br>",
      "<b>Number of AEDs: </b>", aed_num_aeds, "<br>",
      "<b>Location: </b>", location, "<br>",
      "<b>Borough: </b>", borough, "<br>",
      "<b>Trained Personnel: </b>", aed_num_person_trained
    ),
    group = "AED Locations"
  ) |>

  addLayersControl(
    overlayGroups = c("AED Locations"),
    options = layersControlOptions(collapsed = FALSE)
  )
```

**Disclaimer**: when mapping the AED locations, it was discovered that several locations had been coded incorrectly into the wrong borough.

Source: NYC Open Data (DOHMH)