---
title: "Maps_For_Shiny"
author: "Maliha Safdar"
date: "2025-12-02"
output: html_document
---

```{r, include = FALSE} 
library(tidyverse)
library(stringr)
library(leaflet)
library(tigris)
options(tigris_use_cache = TRUE)
library(sf)
library(RColorBrewer)
```


```{r}
# Importing dataset

traffic_volume_df = read.csv("clean_data/traffic_clean.csv")

aed_inventory_df = read.csv("clean_data/aed_clean.csv")

```


```{r, adding location variable}
aed_clean = aed_inventory_df |>
  mutate(location = str_replace(location_point,"^POINT\\s*", "")
         )
```


```{r, setup of NYC Boroughs}

boroughs = counties(state = "NY", cb = TRUE) |>
  filter(NAME %in% c("Bronx", "Kings", "New York", "Queens", "Richmond")) |>
  st_transform(4326) |>
  mutate(
    borough = case_when(
      NAME == "Bronx" ~ "Bronx",
      NAME == "Kings" ~ "Brooklyn",
      NAME == "New York" ~ "Manhattan",
      NAME == "Queens" ~ "Queens",
      NAME == "Richmond" ~ "Staten Island"
    )
  )

boro_pal <- colorFactor(
  palette = "Set1",
  domain = boroughs$borough
)
```


```{r, AED and borough mapping}

aed_map_icon <- makeIcon(
  iconUrl = "icons/map_logo.png",
  iconWidth = 15,             
  iconHeight = 15
)

leaflet() |>
  addProviderTiles(providers$CartoDB.Positron) |>
   addPolygons(
    data = boroughs,
    fillColor = ~boro_pal(borough),
    fillOpacity = 0.3,
    weight = 2,
    color = ~boro_pal(borough),
    popup = ~borough,
    group = "Boroughs"
  ) |>
   addLegend(
  "bottomright",
  pal = boro_pal,
  values = boroughs$borough,
  title = "Borough"
) |>
  addMarkers(
    data = aed_clean,
    lng = ~longitude,
    lat = ~latitude,
    icon = aed_map_icon,
    popup = ~paste0(
      "<b>Location Name: </b>", entity_name, "<br>",
      "<b>Number of AEDs: </b>", aed_num_aeds, "<br>",
      "<b>Location: </b>", location, "<br>",
      "<b>Borough: </b>", borough, "<br>",
      "<b>Trained Personnel: </b>", aed_num_person_trained
    ),
    group = "AED Locations"
  ) |>

  addLayersControl(
    overlayGroups = c("Boroughs"),
    options = layersControlOptions(collapsed = FALSE)
  )
```


```{r, traffic intersections on a borough level}

# Converting wkt to sf point geometry (NYC uses EPSG 2263)
traffic_sf = traffic_volume_df |>
  mutate(
    geometry = st_as_sfc(wkt_geom, crs = 2263)
    ) |>
  st_as_sf() |>
  st_transform(4326) |>
  mutate(
    lon = st_coordinates(geometry)[,1],
                         lat = st_coordinates(geometry)[,2]
    ) # Converting to lat/long for leaflet

#Aggregating traffic volumes

traffic_summary = traffic_sf |>
  group_by(segment_id,street,from_st,to_st,boro) |>
  summarise(
    mean_vol = mean(vol, na.rm = TRUE),
    max_vol = max(vol, na.rm = TRUE),
    n_obs = n(),
    lon = first(lon),
    lat = first(lat),
    .groups = "drop"
  )

traffic_summary = st_as_sf(traffic_summary,
                           coords = c("lon", "lat"),
                           crs = 4326)

#mapping overall traffic volume in the dataset

traffic_summary |>
  leaflet() |>
  addProviderTiles(providers$OpenStreetMap) |>
   addPolygons(
    data = boroughs,
    fillColor = ~boro_pal(borough),
    fillOpacity = 0.3,
    weight = 2,
    color = ~boro_pal(borough),
    popup = ~borough,
    group = "Boroughs"
  ) |>
   addLegend(
  "topleft",
  pal = boro_pal,
  values = boroughs$borough,
  title = "Borough"
) |>
  addProviderTiles(providers$OpenStreetMap) |>
  addCircleMarkers(
    lng = ~lon,
    lat = ~lat,
    radius = ~ scales::rescale(mean_vol, to = c(3,15)),
    color= ~ case_when(
      mean_vol < 200 ~ "lightgreen",
      mean_vol < 400 ~ "orange",
      TRUE ~ "red"
    ),
    stroke = FALSE,
    fillOpacity = 0.7,
    popup = ~paste0(
      "<b>Street: </b>", street, "<b>",
      "<b>From: </b>", from_st, "<b>",
      "<b>To: </b>", to_st, "<b>",
      "<b>Avg Volume: </b>", round(mean_vol), "<b>",
      "<b>Observations: </b>", n_obs
    ),
    group = "Traffic Volume"
  ) |>
  addLayersControl(
    overlayGroups = c("Boroughs", "Traffic Volume"),
    options = layersControlOptions(collapsed = FALSE)
  ) |>
  addLegend(
    position = "bottomright",
    colors = c("lightgreen", "orange", "red"),
    labels = c("Low", "Medium", "High"),
    title = "Mean Traffic Volume"
  )
```