---
title: "Maps"
author: "Juhi Mattekatt"
date: "2025-12-01"
output: html_document
---

```{r,setup, include=FALSE}
library(tidyverse)
library(stringr)
library(leaflet)
library(tigris)
library(sf)
library(RColorBrewer)
```


```{r, echo=FALSE, include=FALSE}
# Importing dataset

traffic_volume_df = read.csv("clean_data/traffic_clean.csv")

aed_inventory_df = read.csv("clean_data/aed_clean.csv")

```


```{r adding location variable, echo=FALSE, include=FALSE}
aed_clean = aed_inventory_df |>
  mutate(location = str_replace(location_point,"^POINT\\s*", "")
         )
```


```{r, setup of NYC Boroughs, echo=FALSE, include=FALSE}

boroughs = counties(state = "NY", cb = TRUE) |>
  filter(NAME %in% c("Bronx", "Kings", "New York", "Queens", "Richmond")) |>
  st_transform(4326) |>
  mutate(
    borough = case_when(
      NAME == "Bronx" ~ "Bronx",
      NAME == "Kings" ~ "Brooklyn",
      NAME == "New York" ~ "Manhattan",
      NAME == "Queens" ~ "Queens",
      NAME == "Richmond" ~ "Staten Island"
    )
  )

boro_pal <- colorFactor(
  palette = "Set1",
  domain = boroughs$borough
)
```


```{r, AED and borough mapping, echo=FALSE}

aed_map_icon <- makeIcon(
  iconUrl = "icons/map_logo.png",
  iconWidth = 15,             
  iconHeight = 15
)

aed_map = leaflet() |>
  addProviderTiles(providers$CartoDB.Positron) |>
   addPolygons(
    data = boroughs,
    fillColor = ~boro_pal(borough),
    fillOpacity = 0.3,
    weight = 2,
    color = ~boro_pal(borough),
    popup = ~borough,
    group = "Boroughs"
  ) |>
   addLegend(
  "bottomright",
  pal = boro_pal,
  values = boroughs$borough,
  title = "Borough"
) |>
  addMarkers(
    data = aed_clean,
    lng = ~longitude,
    lat = ~latitude,
    icon = aed_map_icon,
    popup = ~paste0(
      "<b>Location Name: </b>", entity_name, "<br>",
      "<b>Number of AEDs: </b>", aed_num_aeds, "<br>",
      "<b>Location: </b>", location, "<br>",
      "<b>Borough: </b>", borough, "<br>",
      "<b>Trained Personnel: </b>", aed_num_person_trained
    ),
    group = "AED Locations"
  ) |>

  addLayersControl(
    overlayGroups = c("AED Locations"),
    options = layersControlOptions(collapsed = FALSE)
  )
```
```{r import_prepare, echo=FALSE}
# import and prepare traffic data
traffic_summary = read.csv("./clean_data/traffic_clean.csv") %>% 
  group_by(segment_id) %>%
  summarize(total_volume = sum(vol, na.rm = TRUE), avg_volume = mean(vol, na.rm = TRUE), .groups = "drop") #summary volume for intersections

traffic_points = read.csv("./clean_data/traffic_clean.csv") %>%
  st_as_sf(wkt = "wkt_geom", crs = 2263) %>%  #convert wkt_geom to longitude and latitude system for mapping
  st_transform(4326)

traffic = traffic_points %>%
  left_join(traffic_summary, by = "segment_id") %>% 
  select(-request_id, -yr, -m, -d, -hh, -mm, -vol) %>% 
  group_by(segment_id) %>% #use instead of distinct becasue distinct takes too long
  slice(1) %>%
  ungroup()
 
  
```


```{r, mapping, echo = FALSE}
traffic_map = leaflet(traffic) %>%
  addProviderTiles("CartoDB.Positron") %>% #simple background 
  addCircleMarkers(
    radius = 3,
    color = ~colorNumeric("RdYlBu", avg_volume)(avg_volume),  #average volume scale by color
    fillOpacity = 0.7,
    popup = ~paste0(
      "<b>Street: ", street, "</b><br>",
      from_st, " → ", to_st, "<br>",
      "Segment ID: ", segment_id, "<br>",
      "Direction: ", direction, "<br>",
      "Total Volume: ", total_volume, "<br>",
      "Average Volume: ", avg_volume, "<br>")) %>%
  addLegend(
    position = "bottomright",
    pal = colorNumeric("RdYlBu", traffic$avg_volume),
    values = traffic$avg_volume,
    title = "Average Volume") 
```

```{r}
library(leafsync)

sync(aed_map, traffic_map)
```

