<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Statistical Analyses</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Exploratory Data Analysis
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="exploratory_datasets.html">Data Exploration</a>
    </li>
    <li>
      <a href="analysis.html">Statistical Analyses</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Dashboard and Maps
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="https://juhimatt.shinyapps.io/shiny_app/">Interactive Map for AED and Traffic Distribution</a>
    </li>
    <li>
      <a href="AED_Visual.html">AED Locations in NYC</a>
    </li>
    <li>
      <a href="traffic_visual.html">Traffic Volume</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="profile.html">Team Profile</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Communications
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="report.html">Report</a>
    </li>
    <li>
      <a href="project_proposal.html">Proposal</a>
    </li>
  </ul>
</li>
<li>
  <a href="https://github.com/medhatulsyani/p8105_final">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore"><strong>Statistical Analyses</strong></h1>

</div>


<p>This page includes the statistical analyses performed to infer the
relationship between AED density and traffic volume. The analyses
performed were:</p>
<ol style="list-style-type: decimal">
<li>Linear regression for mean traffic across boroughs,</li>
<li>Linear regression for mean AEDs across boroughs,</li>
<li>Correlation between AED density and mean traffic volume.</li>
</ol>
<p>Additionally, a derived metric was created for the Traffic Burden
Ratio to highlight the boroughs with the highest traffic congestion and
lowest AED coverage.</p>
<div
id="linear-model-for-mean-traffic-volume-across-boroughs-set-manhattan-as-reference"
class="section level3">
<h3>Linear model for mean traffic volume across boroughs, set Manhattan
as reference</h3>
<pre class="r"><code>traffic_volume_df$boro = as.factor(traffic_volume_df$boro)
traffic_volume_df$boro = relevel(traffic_volume_df$boro, ref = &quot;Manhattan&quot;)
traffic_linear_model = lm(vol ~ boro, data = traffic_volume_df)
summary(traffic_linear_model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = vol ~ boro, data = traffic_volume_df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -147.60  -94.75  -54.67   21.25 2069.25 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       147.5972     0.6121  241.12   &lt;2e-16 ***
## boroBronx         -61.0661     0.9409  -64.90   &lt;2e-16 ***
## boroBrooklyn      -24.9223     0.7615  -32.73   &lt;2e-16 ***
## boroQueens        -29.8485     0.7596  -39.29   &lt;2e-16 ***
## boroStaten Island -38.6350     1.3119  -29.45   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 181.6 on 500720 degrees of freedom
## Multiple R-squared:  0.008664,   Adjusted R-squared:  0.008656 
## F-statistic:  1094 on 4 and 500720 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>On average, every borough has less traffic volume when compared to
that of Manhattan. On average, Manhattan has 147.6 cars worth of traffic
volume at a given intersection. The mean traffic volume in The Bronx is
61.1 cars less than that of Manhattan at a given intersection. The mean
traffic volume in Brooklyn is 24.9 cars less than that of Manhattan at a
given intersection. The mean traffic volume in Queens is 29.8 cars less
than that of Manhattan at a given intersection. The mean traffic volume
in Staten Island is 38.6 cars less than that of Manhattan at a given
intersection.</p>
</div>
<div
id="linear-model-for-mean-aed-across-boroughs-set-manhattan-as-reference"
class="section level3">
<h3>Linear model for mean AED across boroughs, set Manhattan as
reference</h3>
<pre class="r"><code>aed_inventory_df$borough = as.factor(aed_inventory_df$borough)
aed_inventory_df$borough = relevel(aed_inventory_df$borough, ref = &quot;Manhattan&quot;)
aed_linear_model = lm(aed_num_aeds ~ borough, data = aed_inventory_df)
summary(aed_linear_model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = aed_num_aeds ~ borough, data = aed_inventory_df)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -1.795 -0.795 -0.478 -0.103 61.205 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           1.79520    0.04682  38.343  &lt; 2e-16 ***
## boroughBronx         -0.75269    0.10163  -7.406 1.44e-13 ***
## boroughBrooklyn      -0.69244    0.08882  -7.796 7.24e-15 ***
## boroughQueens        -0.31719    0.09348  -3.393 0.000694 ***
## boroughStaten Island -0.56621    0.15966  -3.546 0.000393 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.835 on 7634 degrees of freedom
## Multiple R-squared:  0.01247,    Adjusted R-squared:  0.01195 
## F-statistic: 24.09 on 4 and 7634 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>On average, every borough has less AED density when compared to that
of Manhattan. On average, the AED density in Manhattan is 1.795 AED
access points per location. The mean AED density in The Bronx is .75
less AED access points per location compared to that of Manhattan. The
mean AED density in Brooklyn is .69 less AED access points per location
compared to that of Manhattan. The mean AED density in Queens is .32
less AED access points per location compared to that of Manhattan. The
mean AED density in Staten Island is .57 less AED access points per
location compared to that of Manhattan.</p>
</div>
<div
id="pearson-correlation-between-aed-density-and-mean-traffic-volume"
class="section level3">
<h3>Pearson correlation between AED density and mean traffic volume</h3>
<pre class="r"><code>mean_traffic =
  traffic_volume_df %&gt;% 
  group_by(boro) %&gt;% 
  summarize(mean_traffic = mean(vol, na.rm = TRUE))

aed_density = aed_inventory_df %&gt;%
  group_by(borough) %&gt;%
  summarize(total_aeds = sum(aed_num_aeds, na.rm = TRUE))

aed_traffic = mean_traffic %&gt;% 
  full_join(aed_density, by = c(&quot;boro&quot; = &quot;borough&quot;))

cor_result =
  cor.test(aed_traffic$total_aeds, aed_traffic$mean_traffic)

print(cor_result)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  aed_traffic$total_aeds and aed_traffic$mean_traffic
## t = 2.5387, df = 3, p-value = 0.08478
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.2072580  0.9881544
## sample estimates:
##       cor 
## 0.8260589</code></pre>
<p>The resulting Pearson correlation coefficient is 0.826. This
indicates a strong positive correlation between AED density and traffic
volume, but the p-value is greater than 0.05, indicating it is
non-significant.</p>
</div>
<div id="derived-metric" class="section level3">
<h3>Derived metric</h3>
<pre class="r"><code>traffic_summary = traffic_volume_df %&gt;%
  group_by(boro) %&gt;%
  summarize(total_vehicles = sum(vol, na.rm = TRUE))

tbr_df = traffic_summary %&gt;%
  full_join(aed_density, by = c(&quot;boro&quot; = &quot;borough&quot;))

tbr_df = tbr_df %&gt;%
  mutate(TBR = total_vehicles / total_aeds) %&gt;%
  arrange(desc(TBR))

tbr_df</code></pre>
<pre><code>## # A tibble: 5 × 4
##   boro          total_vehicles total_aeds    TBR
##   &lt;fct&gt;                  &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;
## 1 Brooklyn            19709072       1556 12666.
## 2 Queens              19191509       1815 10574.
## 3 Staten Island        2668922        424  6295.
## 4 Bronx                5587491       1030  5425.
## 5 Manhattan           12990181       6583  1973.</code></pre>
<p>The Traffic Burden Ratio seems to be highest in Brooklyn and lowest
in Manhattan. Although traffic is high in Manhattan, there is increased
AED availability which mitigates the potential for a high TBR.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
